// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package SendereCommons.protopackets;

public interface AuthenticationStage1PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthenticationStage1Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes publicKey = 1;</code>
   * @return The publicKey.
   */
  com.google.protobuf.ByteString getPublicKey();

  /**
   * <code>bytes encryptedSecret = 2;</code>
   * @return The encryptedSecret.
   */
  com.google.protobuf.ByteString getEncryptedSecret();

  /**
   * <code>int64 secret = 3;</code>
   * @return The secret.
   */
  long getSecret();
}
