// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package SendereCommons.protopackets;

/**
 * Protobuf type {@code AuthenticationStage1Packet}
 */
public final class AuthenticationStage1Packet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AuthenticationStage1Packet)
    AuthenticationStage1PacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AuthenticationStage1Packet.newBuilder() to construct.
  private AuthenticationStage1Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuthenticationStage1Packet() {
    publicKey_ = com.google.protobuf.ByteString.EMPTY;
    encryptedSecret_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AuthenticationStage1Packet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AuthenticationStage1Packet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            publicKey_ = input.readBytes();
            break;
          }
          case 18: {

            encryptedSecret_ = input.readBytes();
            break;
          }
          case 24: {

            secret_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SendereCommons.protopackets.PacketProtos.internal_static_AuthenticationStage1Packet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SendereCommons.protopackets.PacketProtos.internal_static_AuthenticationStage1Packet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SendereCommons.protopackets.AuthenticationStage1Packet.class, SendereCommons.protopackets.AuthenticationStage1Packet.Builder.class);
  }

  public static final int PUBLICKEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString publicKey_;
  /**
   * <code>bytes publicKey = 1;</code>
   * @return The publicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPublicKey() {
    return publicKey_;
  }

  public static final int ENCRYPTEDSECRET_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString encryptedSecret_;
  /**
   * <code>bytes encryptedSecret = 2;</code>
   * @return The encryptedSecret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedSecret() {
    return encryptedSecret_;
  }

  public static final int SECRET_FIELD_NUMBER = 3;
  private long secret_;
  /**
   * <code>int64 secret = 3;</code>
   * @return The secret.
   */
  @java.lang.Override
  public long getSecret() {
    return secret_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!publicKey_.isEmpty()) {
      output.writeBytes(1, publicKey_);
    }
    if (!encryptedSecret_.isEmpty()) {
      output.writeBytes(2, encryptedSecret_);
    }
    if (secret_ != 0L) {
      output.writeInt64(3, secret_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!publicKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, publicKey_);
    }
    if (!encryptedSecret_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, encryptedSecret_);
    }
    if (secret_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, secret_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SendereCommons.protopackets.AuthenticationStage1Packet)) {
      return super.equals(obj);
    }
    SendereCommons.protopackets.AuthenticationStage1Packet other = (SendereCommons.protopackets.AuthenticationStage1Packet) obj;

    if (!getPublicKey()
        .equals(other.getPublicKey())) return false;
    if (!getEncryptedSecret()
        .equals(other.getEncryptedSecret())) return false;
    if (getSecret()
        != other.getSecret()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPublicKey().hashCode();
    hash = (37 * hash) + ENCRYPTEDSECRET_FIELD_NUMBER;
    hash = (53 * hash) + getEncryptedSecret().hashCode();
    hash = (37 * hash) + SECRET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSecret());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SendereCommons.protopackets.AuthenticationStage1Packet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SendereCommons.protopackets.AuthenticationStage1Packet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AuthenticationStage1Packet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AuthenticationStage1Packet)
      SendereCommons.protopackets.AuthenticationStage1PacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SendereCommons.protopackets.PacketProtos.internal_static_AuthenticationStage1Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SendereCommons.protopackets.PacketProtos.internal_static_AuthenticationStage1Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SendereCommons.protopackets.AuthenticationStage1Packet.class, SendereCommons.protopackets.AuthenticationStage1Packet.Builder.class);
    }

    // Construct using SendereCommons.protopackets.AuthenticationStage1Packet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      publicKey_ = com.google.protobuf.ByteString.EMPTY;

      encryptedSecret_ = com.google.protobuf.ByteString.EMPTY;

      secret_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SendereCommons.protopackets.PacketProtos.internal_static_AuthenticationStage1Packet_descriptor;
    }

    @java.lang.Override
    public SendereCommons.protopackets.AuthenticationStage1Packet getDefaultInstanceForType() {
      return SendereCommons.protopackets.AuthenticationStage1Packet.getDefaultInstance();
    }

    @java.lang.Override
    public SendereCommons.protopackets.AuthenticationStage1Packet build() {
      SendereCommons.protopackets.AuthenticationStage1Packet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public SendereCommons.protopackets.AuthenticationStage1Packet buildPartial() {
      SendereCommons.protopackets.AuthenticationStage1Packet result = new SendereCommons.protopackets.AuthenticationStage1Packet(this);
      result.publicKey_ = publicKey_;
      result.encryptedSecret_ = encryptedSecret_;
      result.secret_ = secret_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SendereCommons.protopackets.AuthenticationStage1Packet) {
        return mergeFrom((SendereCommons.protopackets.AuthenticationStage1Packet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SendereCommons.protopackets.AuthenticationStage1Packet other) {
      if (other == SendereCommons.protopackets.AuthenticationStage1Packet.getDefaultInstance()) return this;
      if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
        setPublicKey(other.getPublicKey());
      }
      if (other.getEncryptedSecret() != com.google.protobuf.ByteString.EMPTY) {
        setEncryptedSecret(other.getEncryptedSecret());
      }
      if (other.getSecret() != 0L) {
        setSecret(other.getSecret());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SendereCommons.protopackets.AuthenticationStage1Packet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SendereCommons.protopackets.AuthenticationStage1Packet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes publicKey = 1;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }
    /**
     * <code>bytes publicKey = 1;</code>
     * @param value The publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      publicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes publicKey = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKey() {
      
      publicKey_ = getDefaultInstance().getPublicKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString encryptedSecret_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encryptedSecret = 2;</code>
     * @return The encryptedSecret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedSecret() {
      return encryptedSecret_;
    }
    /**
     * <code>bytes encryptedSecret = 2;</code>
     * @param value The encryptedSecret to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedSecret(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encryptedSecret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes encryptedSecret = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedSecret() {
      
      encryptedSecret_ = getDefaultInstance().getEncryptedSecret();
      onChanged();
      return this;
    }

    private long secret_ ;
    /**
     * <code>int64 secret = 3;</code>
     * @return The secret.
     */
    @java.lang.Override
    public long getSecret() {
      return secret_;
    }
    /**
     * <code>int64 secret = 3;</code>
     * @param value The secret to set.
     * @return This builder for chaining.
     */
    public Builder setSecret(long value) {
      
      secret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 secret = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecret() {
      
      secret_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AuthenticationStage1Packet)
  }

  // @@protoc_insertion_point(class_scope:AuthenticationStage1Packet)
  private static final SendereCommons.protopackets.AuthenticationStage1Packet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SendereCommons.protopackets.AuthenticationStage1Packet();
  }

  public static SendereCommons.protopackets.AuthenticationStage1Packet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthenticationStage1Packet>
      PARSER = new com.google.protobuf.AbstractParser<AuthenticationStage1Packet>() {
    @java.lang.Override
    public AuthenticationStage1Packet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AuthenticationStage1Packet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AuthenticationStage1Packet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthenticationStage1Packet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public SendereCommons.protopackets.AuthenticationStage1Packet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

