// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package sendereCommons.protopackets;

public interface AuthenticationStage2PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthenticationStage2Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes publicKey = 1;</code>
   * @return The publicKey.
   */
  com.google.protobuf.ByteString getPublicKey();

  /**
   * <code>bytes encryptedSecret = 2;</code>
   * @return The encryptedSecret.
   */
  com.google.protobuf.ByteString getEncryptedSecret();
}
