// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package sendereCommons.protopackets;

public interface DiffieHellmanPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DiffieHellmanPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes encodedPublicKey = 1;</code>
   * @return The encodedPublicKey.
   */
  com.google.protobuf.ByteString getEncodedPublicKey();

  /**
   * <code>bool senderGeneratedSecret = 2;</code>
   * @return The senderGeneratedSecret.
   */
  boolean getSenderGeneratedSecret();

  /**
   * <code>bytes iv = 3;</code>
   * @return Whether the iv field is set.
   */
  boolean hasIv();
  /**
   * <code>bytes iv = 3;</code>
   * @return The iv.
   */
  com.google.protobuf.ByteString getIv();
}
