// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package sendereCommons.protopackets;

/**
 * Protobuf type {@code DiffieHellmanPacket}
 */
public final class DiffieHellmanPacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DiffieHellmanPacket)
    DiffieHellmanPacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DiffieHellmanPacket.newBuilder() to construct.
  private DiffieHellmanPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DiffieHellmanPacket() {
    encodedPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    iv_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DiffieHellmanPacket();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DiffieHellmanPacket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            encodedPublicKey_ = input.readBytes();
            break;
          }
          case 16: {

            senderGeneratedSecret_ = input.readBool();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000001;
            iv_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sendereCommons.protopackets.PacketProtos.internal_static_DiffieHellmanPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sendereCommons.protopackets.PacketProtos.internal_static_DiffieHellmanPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sendereCommons.protopackets.DiffieHellmanPacket.class, sendereCommons.protopackets.DiffieHellmanPacket.Builder.class);
  }

  private int bitField0_;
  public static final int ENCODEDPUBLICKEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString encodedPublicKey_;
  /**
   * <code>bytes encodedPublicKey = 1;</code>
   * @return The encodedPublicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncodedPublicKey() {
    return encodedPublicKey_;
  }

  public static final int SENDERGENERATEDSECRET_FIELD_NUMBER = 2;
  private boolean senderGeneratedSecret_;
  /**
   * <code>bool senderGeneratedSecret = 2;</code>
   * @return The senderGeneratedSecret.
   */
  @java.lang.Override
  public boolean getSenderGeneratedSecret() {
    return senderGeneratedSecret_;
  }

  public static final int IV_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString iv_;
  /**
   * <code>bytes iv = 3;</code>
   * @return Whether the iv field is set.
   */
  @java.lang.Override
  public boolean hasIv() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>bytes iv = 3;</code>
   * @return The iv.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIv() {
    return iv_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!encodedPublicKey_.isEmpty()) {
      output.writeBytes(1, encodedPublicKey_);
    }
    if (senderGeneratedSecret_ != false) {
      output.writeBool(2, senderGeneratedSecret_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(3, iv_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!encodedPublicKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, encodedPublicKey_);
    }
    if (senderGeneratedSecret_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, senderGeneratedSecret_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, iv_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sendereCommons.protopackets.DiffieHellmanPacket)) {
      return super.equals(obj);
    }
    sendereCommons.protopackets.DiffieHellmanPacket other = (sendereCommons.protopackets.DiffieHellmanPacket) obj;

    if (!getEncodedPublicKey()
        .equals(other.getEncodedPublicKey())) return false;
    if (getSenderGeneratedSecret()
        != other.getSenderGeneratedSecret()) return false;
    if (hasIv() != other.hasIv()) return false;
    if (hasIv()) {
      if (!getIv()
          .equals(other.getIv())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENCODEDPUBLICKEY_FIELD_NUMBER;
    hash = (53 * hash) + getEncodedPublicKey().hashCode();
    hash = (37 * hash) + SENDERGENERATEDSECRET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSenderGeneratedSecret());
    if (hasIv()) {
      hash = (37 * hash) + IV_FIELD_NUMBER;
      hash = (53 * hash) + getIv().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sendereCommons.protopackets.DiffieHellmanPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sendereCommons.protopackets.DiffieHellmanPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DiffieHellmanPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DiffieHellmanPacket)
      sendereCommons.protopackets.DiffieHellmanPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sendereCommons.protopackets.PacketProtos.internal_static_DiffieHellmanPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sendereCommons.protopackets.PacketProtos.internal_static_DiffieHellmanPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sendereCommons.protopackets.DiffieHellmanPacket.class, sendereCommons.protopackets.DiffieHellmanPacket.Builder.class);
    }

    // Construct using sendereCommons.protopackets.DiffieHellmanPacket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      encodedPublicKey_ = com.google.protobuf.ByteString.EMPTY;

      senderGeneratedSecret_ = false;

      iv_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sendereCommons.protopackets.PacketProtos.internal_static_DiffieHellmanPacket_descriptor;
    }

    @java.lang.Override
    public sendereCommons.protopackets.DiffieHellmanPacket getDefaultInstanceForType() {
      return sendereCommons.protopackets.DiffieHellmanPacket.getDefaultInstance();
    }

    @java.lang.Override
    public sendereCommons.protopackets.DiffieHellmanPacket build() {
      sendereCommons.protopackets.DiffieHellmanPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sendereCommons.protopackets.DiffieHellmanPacket buildPartial() {
      sendereCommons.protopackets.DiffieHellmanPacket result = new sendereCommons.protopackets.DiffieHellmanPacket(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.encodedPublicKey_ = encodedPublicKey_;
      result.senderGeneratedSecret_ = senderGeneratedSecret_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.iv_ = iv_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sendereCommons.protopackets.DiffieHellmanPacket) {
        return mergeFrom((sendereCommons.protopackets.DiffieHellmanPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sendereCommons.protopackets.DiffieHellmanPacket other) {
      if (other == sendereCommons.protopackets.DiffieHellmanPacket.getDefaultInstance()) return this;
      if (other.getEncodedPublicKey() != com.google.protobuf.ByteString.EMPTY) {
        setEncodedPublicKey(other.getEncodedPublicKey());
      }
      if (other.getSenderGeneratedSecret() != false) {
        setSenderGeneratedSecret(other.getSenderGeneratedSecret());
      }
      if (other.hasIv()) {
        setIv(other.getIv());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sendereCommons.protopackets.DiffieHellmanPacket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sendereCommons.protopackets.DiffieHellmanPacket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString encodedPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encodedPublicKey = 1;</code>
     * @return The encodedPublicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncodedPublicKey() {
      return encodedPublicKey_;
    }
    /**
     * <code>bytes encodedPublicKey = 1;</code>
     * @param value The encodedPublicKey to set.
     * @return This builder for chaining.
     */
    public Builder setEncodedPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encodedPublicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes encodedPublicKey = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncodedPublicKey() {
      
      encodedPublicKey_ = getDefaultInstance().getEncodedPublicKey();
      onChanged();
      return this;
    }

    private boolean senderGeneratedSecret_ ;
    /**
     * <code>bool senderGeneratedSecret = 2;</code>
     * @return The senderGeneratedSecret.
     */
    @java.lang.Override
    public boolean getSenderGeneratedSecret() {
      return senderGeneratedSecret_;
    }
    /**
     * <code>bool senderGeneratedSecret = 2;</code>
     * @param value The senderGeneratedSecret to set.
     * @return This builder for chaining.
     */
    public Builder setSenderGeneratedSecret(boolean value) {
      
      senderGeneratedSecret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool senderGeneratedSecret = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderGeneratedSecret() {
      
      senderGeneratedSecret_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes iv = 3;</code>
     * @return Whether the iv field is set.
     */
    @java.lang.Override
    public boolean hasIv() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>bytes iv = 3;</code>
     * @return The iv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }
    /**
     * <code>bytes iv = 3;</code>
     * @param value The iv to set.
     * @return This builder for chaining.
     */
    public Builder setIv(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      iv_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes iv = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIv() {
      bitField0_ = (bitField0_ & ~0x00000001);
      iv_ = getDefaultInstance().getIv();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DiffieHellmanPacket)
  }

  // @@protoc_insertion_point(class_scope:DiffieHellmanPacket)
  private static final sendereCommons.protopackets.DiffieHellmanPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sendereCommons.protopackets.DiffieHellmanPacket();
  }

  public static sendereCommons.protopackets.DiffieHellmanPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DiffieHellmanPacket>
      PARSER = new com.google.protobuf.AbstractParser<DiffieHellmanPacket>() {
    @java.lang.Override
    public DiffieHellmanPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DiffieHellmanPacket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DiffieHellmanPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DiffieHellmanPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sendereCommons.protopackets.DiffieHellmanPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

