// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package sendereCommons.protopackets;

public interface DiscoveryPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DiscoveryPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 suid = 1;</code>
   * @return The suid.
   */
  long getSuid();

  /**
   * <code>bytes address = 2;</code>
   * @return The address.
   */
  com.google.protobuf.ByteString getAddress();

  /**
   * <code>int32 port = 3;</code>
   * @return The port.
   */
  int getPort();
}
