// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package sendereCommons.protopackets;

/**
 * Protobuf type {@code EncryptionCheckPacket}
 */
public final class EncryptionCheckPacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EncryptionCheckPacket)
    EncryptionCheckPacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EncryptionCheckPacket.newBuilder() to construct.
  private EncryptionCheckPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EncryptionCheckPacket() {
    encrypted_ = com.google.protobuf.ByteString.EMPTY;
    cleartext_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EncryptionCheckPacket();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EncryptionCheckPacket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            encrypted_ = input.readBytes();
            break;
          }
          case 18: {

            cleartext_ = input.readBytes();
            break;
          }
          case 24: {

            senderTrusts_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sendereCommons.protopackets.PacketProtos.internal_static_EncryptionCheckPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sendereCommons.protopackets.PacketProtos.internal_static_EncryptionCheckPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sendereCommons.protopackets.EncryptionCheckPacket.class, sendereCommons.protopackets.EncryptionCheckPacket.Builder.class);
  }

  public static final int ENCRYPTED_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString encrypted_;
  /**
   * <code>bytes encrypted = 1;</code>
   * @return The encrypted.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncrypted() {
    return encrypted_;
  }

  public static final int CLEARTEXT_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString cleartext_;
  /**
   * <code>bytes cleartext = 2;</code>
   * @return The cleartext.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCleartext() {
    return cleartext_;
  }

  public static final int SENDERTRUSTS_FIELD_NUMBER = 3;
  private boolean senderTrusts_;
  /**
   * <code>bool senderTrusts = 3;</code>
   * @return The senderTrusts.
   */
  @java.lang.Override
  public boolean getSenderTrusts() {
    return senderTrusts_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!encrypted_.isEmpty()) {
      output.writeBytes(1, encrypted_);
    }
    if (!cleartext_.isEmpty()) {
      output.writeBytes(2, cleartext_);
    }
    if (senderTrusts_ != false) {
      output.writeBool(3, senderTrusts_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!encrypted_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, encrypted_);
    }
    if (!cleartext_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, cleartext_);
    }
    if (senderTrusts_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, senderTrusts_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sendereCommons.protopackets.EncryptionCheckPacket)) {
      return super.equals(obj);
    }
    sendereCommons.protopackets.EncryptionCheckPacket other = (sendereCommons.protopackets.EncryptionCheckPacket) obj;

    if (!getEncrypted()
        .equals(other.getEncrypted())) return false;
    if (!getCleartext()
        .equals(other.getCleartext())) return false;
    if (getSenderTrusts()
        != other.getSenderTrusts()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENCRYPTED_FIELD_NUMBER;
    hash = (53 * hash) + getEncrypted().hashCode();
    hash = (37 * hash) + CLEARTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getCleartext().hashCode();
    hash = (37 * hash) + SENDERTRUSTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSenderTrusts());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sendereCommons.protopackets.EncryptionCheckPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sendereCommons.protopackets.EncryptionCheckPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EncryptionCheckPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EncryptionCheckPacket)
      sendereCommons.protopackets.EncryptionCheckPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sendereCommons.protopackets.PacketProtos.internal_static_EncryptionCheckPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sendereCommons.protopackets.PacketProtos.internal_static_EncryptionCheckPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sendereCommons.protopackets.EncryptionCheckPacket.class, sendereCommons.protopackets.EncryptionCheckPacket.Builder.class);
    }

    // Construct using sendereCommons.protopackets.EncryptionCheckPacket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      encrypted_ = com.google.protobuf.ByteString.EMPTY;

      cleartext_ = com.google.protobuf.ByteString.EMPTY;

      senderTrusts_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sendereCommons.protopackets.PacketProtos.internal_static_EncryptionCheckPacket_descriptor;
    }

    @java.lang.Override
    public sendereCommons.protopackets.EncryptionCheckPacket getDefaultInstanceForType() {
      return sendereCommons.protopackets.EncryptionCheckPacket.getDefaultInstance();
    }

    @java.lang.Override
    public sendereCommons.protopackets.EncryptionCheckPacket build() {
      sendereCommons.protopackets.EncryptionCheckPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sendereCommons.protopackets.EncryptionCheckPacket buildPartial() {
      sendereCommons.protopackets.EncryptionCheckPacket result = new sendereCommons.protopackets.EncryptionCheckPacket(this);
      result.encrypted_ = encrypted_;
      result.cleartext_ = cleartext_;
      result.senderTrusts_ = senderTrusts_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sendereCommons.protopackets.EncryptionCheckPacket) {
        return mergeFrom((sendereCommons.protopackets.EncryptionCheckPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sendereCommons.protopackets.EncryptionCheckPacket other) {
      if (other == sendereCommons.protopackets.EncryptionCheckPacket.getDefaultInstance()) return this;
      if (other.getEncrypted() != com.google.protobuf.ByteString.EMPTY) {
        setEncrypted(other.getEncrypted());
      }
      if (other.getCleartext() != com.google.protobuf.ByteString.EMPTY) {
        setCleartext(other.getCleartext());
      }
      if (other.getSenderTrusts() != false) {
        setSenderTrusts(other.getSenderTrusts());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sendereCommons.protopackets.EncryptionCheckPacket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sendereCommons.protopackets.EncryptionCheckPacket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString encrypted_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encrypted = 1;</code>
     * @return The encrypted.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncrypted() {
      return encrypted_;
    }
    /**
     * <code>bytes encrypted = 1;</code>
     * @param value The encrypted to set.
     * @return This builder for chaining.
     */
    public Builder setEncrypted(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encrypted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes encrypted = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncrypted() {
      
      encrypted_ = getDefaultInstance().getEncrypted();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString cleartext_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes cleartext = 2;</code>
     * @return The cleartext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCleartext() {
      return cleartext_;
    }
    /**
     * <code>bytes cleartext = 2;</code>
     * @param value The cleartext to set.
     * @return This builder for chaining.
     */
    public Builder setCleartext(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cleartext_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes cleartext = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCleartext() {
      
      cleartext_ = getDefaultInstance().getCleartext();
      onChanged();
      return this;
    }

    private boolean senderTrusts_ ;
    /**
     * <code>bool senderTrusts = 3;</code>
     * @return The senderTrusts.
     */
    @java.lang.Override
    public boolean getSenderTrusts() {
      return senderTrusts_;
    }
    /**
     * <code>bool senderTrusts = 3;</code>
     * @param value The senderTrusts to set.
     * @return This builder for chaining.
     */
    public Builder setSenderTrusts(boolean value) {
      
      senderTrusts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool senderTrusts = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderTrusts() {
      
      senderTrusts_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EncryptionCheckPacket)
  }

  // @@protoc_insertion_point(class_scope:EncryptionCheckPacket)
  private static final sendereCommons.protopackets.EncryptionCheckPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sendereCommons.protopackets.EncryptionCheckPacket();
  }

  public static sendereCommons.protopackets.EncryptionCheckPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EncryptionCheckPacket>
      PARSER = new com.google.protobuf.AbstractParser<EncryptionCheckPacket>() {
    @java.lang.Override
    public EncryptionCheckPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EncryptionCheckPacket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EncryptionCheckPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EncryptionCheckPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sendereCommons.protopackets.EncryptionCheckPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

