// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package sendereCommons.protopackets;

public final class PacketProtos {
  private PacketProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DiscoveryPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DiscoveryPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IdentificationPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IdentificationPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PongPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PongPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteErrorPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoteErrorPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendRequestPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendRequestPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendResponsePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendResponsePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateFilePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateFilePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateDirectoryPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateDirectoryPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RawDataPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RawDataPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CloseFilePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CloseFilePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransmissionControlPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransmissionControlPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DiffieHellmanPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DiffieHellmanPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EncryptionCheckPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EncryptionCheckPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ping-packet.proto\">\n\017DiscoveryPacket\022\014" +
      "\n\004suid\030\001 \001(\003\022\017\n\007address\030\002 \001(\014\022\014\n\004port\030\003 " +
      "\001(\005\"^\n\024IdentificationPacket\022\020\n\010nickname\030" +
      "\001 \001(\t\022\030\n\020remoteIdentified\030\002 \001(\010\022\032\n\022suppr" +
      "otEnctryption\030\003 \001(\010\"\\\n\nPingPacket\022\014\n\004sui" +
      "d\030\001 \001(\003\022\020\n\010nickname\030\002 \001(\t\022\023\n\013supportGzip" +
      "\030\003 \001(\010\022\031\n\021supportEncryption\030\004 \001(\010\"\\\n\nPon" +
      "gPacket\022\014\n\004suid\030\001 \001(\003\022\020\n\010nickname\030\002 \001(\t\022" +
      "\023\n\013supportGzip\030\003 \001(\010\022\031\n\021supportEncryptio" +
      "n\030\004 \001(\010\"\350\001\n\021RemoteErrorPacket\022/\n\terrorTy" +
      "pe\030\001 \001(\0162\034.RemoteErrorPacket.ErrorType\022\031" +
      "\n\014extraMessage\030\002 \001(\tH\000\210\001\001\"v\n\tErrorType\022\020" +
      "\n\014NOT_PROTOBUF\020\000\022\027\n\023UNRECOGNIZED_PACKET\020" +
      "\001\022\022\n\016INVALID_FORMAT\020\002\022\024\n\020CHAT_NOT_ALLOWE" +
      "D\020\003\022\024\n\020SEND_NOT_ALLOWED\020\004B\017\n\r_extraMessa" +
      "ge\"\032\n\nTextPacket\022\014\n\004text\030\001 \001(\t\"R\n\021SendRe" +
      "questPacket\022\026\n\016transmissionId\030\001 \001(\003\022\023\n\013i" +
      "sDirectory\030\002 \001(\010\022\020\n\010fileName\030\003 \001(\t\">\n\022Se" +
      "ndResponsePacket\022\026\n\016transmissionId\030\001 \001(\003" +
      "\022\020\n\010accepted\030\002 \001(\010\"<\n\020CreateFilePacket\022\026" +
      "\n\016transmissionId\030\001 \001(\003\022\020\n\010fileName\030\002 \001(\t" +
      "\"A\n\025CreateDirectoryPacket\022\026\n\016transmissio" +
      "nId\030\001 \001(\003\022\020\n\010fileName\030\002 \001(\t\"5\n\rRawDataPa" +
      "cket\022\026\n\016transmissionId\030\001 \001(\003\022\014\n\004data\030\002 \001" +
      "(\014\")\n\017CloseFilePacket\022\026\n\016transmissionId\030" +
      "\001 \001(\003\"\314\001\n\031TransmissionControlPacket\022\026\n\016t" +
      "ransmissionId\030\001 \001(\003\0221\n\006signal\030\002 \001(\0162!.Tr" +
      "ansmissionControlPacket.Signal\"d\n\006Signal" +
      "\022\024\n\020SENDING_CANCELED\020\000\022\026\n\022RECEIVING_CANC" +
      "ELED\020\001\022\024\n\020SENDING_COMPLETE\020\002\022\026\n\022RECEIVIN" +
      "G_COMPLETE\020\003\"f\n\023DiffieHellmanPacket\022\030\n\020e" +
      "ncodedPublicKey\030\001 \001(\014\022\035\n\025senderGenerated" +
      "Secret\030\002 \001(\010\022\017\n\002iv\030\003 \001(\014H\000\210\001\001B\005\n\003_iv\"S\n\025" +
      "EncryptionCheckPacket\022\021\n\tencrypted\030\001 \001(\014" +
      "\022\021\n\tcleartext\030\002 \001(\014\022\024\n\014senderTrusts\030\003 \001(" +
      "\010B-\n\033sendereCommons.protopacketsB\014Packet" +
      "ProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DiscoveryPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DiscoveryPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DiscoveryPacket_descriptor,
        new java.lang.String[] { "Suid", "Address", "Port", });
    internal_static_IdentificationPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IdentificationPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IdentificationPacket_descriptor,
        new java.lang.String[] { "Nickname", "RemoteIdentified", "SupprotEnctryption", });
    internal_static_PingPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PingPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingPacket_descriptor,
        new java.lang.String[] { "Suid", "Nickname", "SupportGzip", "SupportEncryption", });
    internal_static_PongPacket_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PongPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PongPacket_descriptor,
        new java.lang.String[] { "Suid", "Nickname", "SupportGzip", "SupportEncryption", });
    internal_static_RemoteErrorPacket_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RemoteErrorPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoteErrorPacket_descriptor,
        new java.lang.String[] { "ErrorType", "ExtraMessage", "ExtraMessage", });
    internal_static_TextPacket_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_TextPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextPacket_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_SendRequestPacket_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SendRequestPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendRequestPacket_descriptor,
        new java.lang.String[] { "TransmissionId", "IsDirectory", "FileName", });
    internal_static_SendResponsePacket_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SendResponsePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendResponsePacket_descriptor,
        new java.lang.String[] { "TransmissionId", "Accepted", });
    internal_static_CreateFilePacket_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CreateFilePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateFilePacket_descriptor,
        new java.lang.String[] { "TransmissionId", "FileName", });
    internal_static_CreateDirectoryPacket_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_CreateDirectoryPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateDirectoryPacket_descriptor,
        new java.lang.String[] { "TransmissionId", "FileName", });
    internal_static_RawDataPacket_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_RawDataPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RawDataPacket_descriptor,
        new java.lang.String[] { "TransmissionId", "Data", });
    internal_static_CloseFilePacket_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_CloseFilePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CloseFilePacket_descriptor,
        new java.lang.String[] { "TransmissionId", });
    internal_static_TransmissionControlPacket_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_TransmissionControlPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransmissionControlPacket_descriptor,
        new java.lang.String[] { "TransmissionId", "Signal", });
    internal_static_DiffieHellmanPacket_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_DiffieHellmanPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DiffieHellmanPacket_descriptor,
        new java.lang.String[] { "EncodedPublicKey", "SenderGeneratedSecret", "Iv", "Iv", });
    internal_static_EncryptionCheckPacket_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_EncryptionCheckPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EncryptionCheckPacket_descriptor,
        new java.lang.String[] { "Encrypted", "Cleartext", "SenderTrusts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
