// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package sendereCommons.protopackets;

public final class PacketProtos {
  private PacketProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DiscoveryPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DiscoveryPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PongPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PongPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteErrorPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoteErrorPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendRequestPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendRequestPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendResponsePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendResponsePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateFilePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateFilePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateDirectoryPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateDirectoryPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RawDataPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RawDataPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CloseFilePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CloseFilePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransmissionControlPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransmissionControlPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthenticationStage1Packet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthenticationStage1Packet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthenticationStage2Packet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthenticationStage2Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ping-packet.proto\">\n\017DiscoveryPacket\022\014" +
      "\n\004suid\030\001 \001(\003\022\017\n\007address\030\002 \001(\014\022\014\n\004port\030\003 " +
      "\001(\005\"\\\n\nPingPacket\022\014\n\004suid\030\001 \001(\003\022\020\n\010nickn" +
      "ame\030\002 \001(\t\022\023\n\013supportGzip\030\003 \001(\010\022\031\n\021suppor" +
      "tEncryption\030\004 \001(\010\"\\\n\nPongPacket\022\014\n\004suid\030" +
      "\001 \001(\003\022\020\n\010nickname\030\002 \001(\t\022\023\n\013supportGzip\030\003" +
      " \001(\010\022\031\n\021supportEncryption\030\004 \001(\010\"\350\001\n\021Remo" +
      "teErrorPacket\022/\n\terrorType\030\001 \001(\0162\034.Remot" +
      "eErrorPacket.ErrorType\022\031\n\014extraMessage\030\002" +
      " \001(\tH\000\210\001\001\"v\n\tErrorType\022\020\n\014NOT_PROTOBUF\020\000" +
      "\022\027\n\023UNRECOGNIZED_PACKET\020\001\022\022\n\016INVALID_FOR" +
      "MAT\020\002\022\024\n\020CHAT_NOT_ALLOWED\020\003\022\024\n\020SEND_NOT_" +
      "ALLOWED\020\004B\017\n\r_extraMessage\"\032\n\nTextPacket" +
      "\022\014\n\004text\030\001 \001(\t\"R\n\021SendRequestPacket\022\026\n\016t" +
      "ransmissionId\030\001 \001(\003\022\023\n\013isDirectory\030\002 \001(\010" +
      "\022\020\n\010fileName\030\003 \001(\t\">\n\022SendResponsePacket" +
      "\022\026\n\016transmissionId\030\001 \001(\003\022\020\n\010accepted\030\002 \001" +
      "(\010\"<\n\020CreateFilePacket\022\026\n\016transmissionId" +
      "\030\001 \001(\003\022\020\n\010fileName\030\002 \001(\t\"A\n\025CreateDirect" +
      "oryPacket\022\026\n\016transmissionId\030\001 \001(\003\022\020\n\010fil" +
      "eName\030\002 \001(\t\"5\n\rRawDataPacket\022\026\n\016transmis" +
      "sionId\030\001 \001(\003\022\014\n\004data\030\002 \001(\014\")\n\017CloseFileP" +
      "acket\022\026\n\016transmissionId\030\001 \001(\003\"\314\001\n\031Transm" +
      "issionControlPacket\022\026\n\016transmissionId\030\001 " +
      "\001(\003\0221\n\006signal\030\002 \001(\0162!.TransmissionContro" +
      "lPacket.Signal\"d\n\006Signal\022\024\n\020SENDING_CANC" +
      "ELED\020\000\022\026\n\022RECEIVING_CANCELED\020\001\022\024\n\020SENDIN" +
      "G_COMPLETE\020\002\022\026\n\022RECEIVING_COMPLETE\020\003\"X\n\032" +
      "AuthenticationStage1Packet\022\021\n\tpublicKey\030" +
      "\001 \001(\014\022\027\n\017encryptedSecret\030\002 \001(\014\022\016\n\006secret" +
      "\030\003 \001(\003\"H\n\032AuthenticationStage2Packet\022\021\n\t" +
      "publicKey\030\001 \001(\014\022\027\n\017encryptedSecret\030\002 \001(\014" +
      "B-\n\033SendereCommons.protopacketsB\014PacketP" +
      "rotosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DiscoveryPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DiscoveryPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DiscoveryPacket_descriptor,
        new java.lang.String[] { "Suid", "Address", "Port", });
    internal_static_PingPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PingPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingPacket_descriptor,
        new java.lang.String[] { "Suid", "Nickname", "SupportGzip", "SupportEncryption", });
    internal_static_PongPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PongPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PongPacket_descriptor,
        new java.lang.String[] { "Suid", "Nickname", "SupportGzip", "SupportEncryption", });
    internal_static_RemoteErrorPacket_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RemoteErrorPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoteErrorPacket_descriptor,
        new java.lang.String[] { "ErrorType", "ExtraMessage", "ExtraMessage", });
    internal_static_TextPacket_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_TextPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextPacket_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_SendRequestPacket_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SendRequestPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendRequestPacket_descriptor,
        new java.lang.String[] { "TransmissionId", "IsDirectory", "FileName", });
    internal_static_SendResponsePacket_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SendResponsePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendResponsePacket_descriptor,
        new java.lang.String[] { "TransmissionId", "Accepted", });
    internal_static_CreateFilePacket_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_CreateFilePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateFilePacket_descriptor,
        new java.lang.String[] { "TransmissionId", "FileName", });
    internal_static_CreateDirectoryPacket_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CreateDirectoryPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateDirectoryPacket_descriptor,
        new java.lang.String[] { "TransmissionId", "FileName", });
    internal_static_RawDataPacket_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_RawDataPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RawDataPacket_descriptor,
        new java.lang.String[] { "TransmissionId", "Data", });
    internal_static_CloseFilePacket_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_CloseFilePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CloseFilePacket_descriptor,
        new java.lang.String[] { "TransmissionId", });
    internal_static_TransmissionControlPacket_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_TransmissionControlPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransmissionControlPacket_descriptor,
        new java.lang.String[] { "TransmissionId", "Signal", });
    internal_static_AuthenticationStage1Packet_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_AuthenticationStage1Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthenticationStage1Packet_descriptor,
        new java.lang.String[] { "PublicKey", "EncryptedSecret", "Secret", });
    internal_static_AuthenticationStage2Packet_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_AuthenticationStage2Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthenticationStage2Packet_descriptor,
        new java.lang.String[] { "PublicKey", "EncryptedSecret", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
