// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package sendereCommons.protopackets;

/**
 * Protobuf type {@code RemoteErrorPacket}
 */
public final class RemoteErrorPacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RemoteErrorPacket)
    RemoteErrorPacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RemoteErrorPacket.newBuilder() to construct.
  private RemoteErrorPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RemoteErrorPacket() {
    errorType_ = 0;
    extraMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RemoteErrorPacket();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RemoteErrorPacket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            errorType_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            extraMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sendereCommons.protopackets.PacketProtos.internal_static_RemoteErrorPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sendereCommons.protopackets.PacketProtos.internal_static_RemoteErrorPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sendereCommons.protopackets.RemoteErrorPacket.class, sendereCommons.protopackets.RemoteErrorPacket.Builder.class);
  }

  /**
   * Protobuf enum {@code RemoteErrorPacket.ErrorType}
   */
  public enum ErrorType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOT_PROTOBUF = 0;</code>
     */
    NOT_PROTOBUF(0),
    /**
     * <code>UNRECOGNIZED_PACKET = 1;</code>
     */
    UNRECOGNIZED_PACKET(1),
    /**
     * <code>INVALID_FORMAT = 2;</code>
     */
    INVALID_FORMAT(2),
    /**
     * <code>CHAT_NOT_ALLOWED = 3;</code>
     */
    CHAT_NOT_ALLOWED(3),
    /**
     * <code>SEND_NOT_ALLOWED = 4;</code>
     */
    SEND_NOT_ALLOWED(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NOT_PROTOBUF = 0;</code>
     */
    public static final int NOT_PROTOBUF_VALUE = 0;
    /**
     * <code>UNRECOGNIZED_PACKET = 1;</code>
     */
    public static final int UNRECOGNIZED_PACKET_VALUE = 1;
    /**
     * <code>INVALID_FORMAT = 2;</code>
     */
    public static final int INVALID_FORMAT_VALUE = 2;
    /**
     * <code>CHAT_NOT_ALLOWED = 3;</code>
     */
    public static final int CHAT_NOT_ALLOWED_VALUE = 3;
    /**
     * <code>SEND_NOT_ALLOWED = 4;</code>
     */
    public static final int SEND_NOT_ALLOWED_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorType forNumber(int value) {
      switch (value) {
        case 0: return NOT_PROTOBUF;
        case 1: return UNRECOGNIZED_PACKET;
        case 2: return INVALID_FORMAT;
        case 3: return CHAT_NOT_ALLOWED;
        case 4: return SEND_NOT_ALLOWED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorType>() {
            public ErrorType findValueByNumber(int number) {
              return ErrorType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sendereCommons.protopackets.RemoteErrorPacket.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorType[] VALUES = values();

    public static ErrorType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RemoteErrorPacket.ErrorType)
  }

  private int bitField0_;
  public static final int ERRORTYPE_FIELD_NUMBER = 1;
  private int errorType_;
  /**
   * <code>.RemoteErrorPacket.ErrorType errorType = 1;</code>
   * @return The enum numeric value on the wire for errorType.
   */
  @java.lang.Override public int getErrorTypeValue() {
    return errorType_;
  }
  /**
   * <code>.RemoteErrorPacket.ErrorType errorType = 1;</code>
   * @return The errorType.
   */
  @java.lang.Override public sendereCommons.protopackets.RemoteErrorPacket.ErrorType getErrorType() {
    @SuppressWarnings("deprecation")
    sendereCommons.protopackets.RemoteErrorPacket.ErrorType result = sendereCommons.protopackets.RemoteErrorPacket.ErrorType.valueOf(errorType_);
    return result == null ? sendereCommons.protopackets.RemoteErrorPacket.ErrorType.UNRECOGNIZED : result;
  }

  public static final int EXTRAMESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object extraMessage_;
  /**
   * <code>string extraMessage = 2;</code>
   * @return Whether the extraMessage field is set.
   */
  @java.lang.Override
  public boolean hasExtraMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>string extraMessage = 2;</code>
   * @return The extraMessage.
   */
  @java.lang.Override
  public java.lang.String getExtraMessage() {
    java.lang.Object ref = extraMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extraMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string extraMessage = 2;</code>
   * @return The bytes for extraMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtraMessageBytes() {
    java.lang.Object ref = extraMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extraMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (errorType_ != sendereCommons.protopackets.RemoteErrorPacket.ErrorType.NOT_PROTOBUF.getNumber()) {
      output.writeEnum(1, errorType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, extraMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errorType_ != sendereCommons.protopackets.RemoteErrorPacket.ErrorType.NOT_PROTOBUF.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, errorType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, extraMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sendereCommons.protopackets.RemoteErrorPacket)) {
      return super.equals(obj);
    }
    sendereCommons.protopackets.RemoteErrorPacket other = (sendereCommons.protopackets.RemoteErrorPacket) obj;

    if (errorType_ != other.errorType_) return false;
    if (hasExtraMessage() != other.hasExtraMessage()) return false;
    if (hasExtraMessage()) {
      if (!getExtraMessage()
          .equals(other.getExtraMessage())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ERRORTYPE_FIELD_NUMBER;
    hash = (53 * hash) + errorType_;
    if (hasExtraMessage()) {
      hash = (37 * hash) + EXTRAMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getExtraMessage().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sendereCommons.protopackets.RemoteErrorPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sendereCommons.protopackets.RemoteErrorPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RemoteErrorPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RemoteErrorPacket)
      sendereCommons.protopackets.RemoteErrorPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sendereCommons.protopackets.PacketProtos.internal_static_RemoteErrorPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sendereCommons.protopackets.PacketProtos.internal_static_RemoteErrorPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sendereCommons.protopackets.RemoteErrorPacket.class, sendereCommons.protopackets.RemoteErrorPacket.Builder.class);
    }

    // Construct using sendereCommons.protopackets.RemoteErrorPacket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      errorType_ = 0;

      extraMessage_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sendereCommons.protopackets.PacketProtos.internal_static_RemoteErrorPacket_descriptor;
    }

    @java.lang.Override
    public sendereCommons.protopackets.RemoteErrorPacket getDefaultInstanceForType() {
      return sendereCommons.protopackets.RemoteErrorPacket.getDefaultInstance();
    }

    @java.lang.Override
    public sendereCommons.protopackets.RemoteErrorPacket build() {
      sendereCommons.protopackets.RemoteErrorPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sendereCommons.protopackets.RemoteErrorPacket buildPartial() {
      sendereCommons.protopackets.RemoteErrorPacket result = new sendereCommons.protopackets.RemoteErrorPacket(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.errorType_ = errorType_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.extraMessage_ = extraMessage_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sendereCommons.protopackets.RemoteErrorPacket) {
        return mergeFrom((sendereCommons.protopackets.RemoteErrorPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sendereCommons.protopackets.RemoteErrorPacket other) {
      if (other == sendereCommons.protopackets.RemoteErrorPacket.getDefaultInstance()) return this;
      if (other.errorType_ != 0) {
        setErrorTypeValue(other.getErrorTypeValue());
      }
      if (other.hasExtraMessage()) {
        bitField0_ |= 0x00000001;
        extraMessage_ = other.extraMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sendereCommons.protopackets.RemoteErrorPacket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sendereCommons.protopackets.RemoteErrorPacket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int errorType_ = 0;
    /**
     * <code>.RemoteErrorPacket.ErrorType errorType = 1;</code>
     * @return The enum numeric value on the wire for errorType.
     */
    @java.lang.Override public int getErrorTypeValue() {
      return errorType_;
    }
    /**
     * <code>.RemoteErrorPacket.ErrorType errorType = 1;</code>
     * @param value The enum numeric value on the wire for errorType to set.
     * @return This builder for chaining.
     */
    public Builder setErrorTypeValue(int value) {
      
      errorType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.RemoteErrorPacket.ErrorType errorType = 1;</code>
     * @return The errorType.
     */
    @java.lang.Override
    public sendereCommons.protopackets.RemoteErrorPacket.ErrorType getErrorType() {
      @SuppressWarnings("deprecation")
      sendereCommons.protopackets.RemoteErrorPacket.ErrorType result = sendereCommons.protopackets.RemoteErrorPacket.ErrorType.valueOf(errorType_);
      return result == null ? sendereCommons.protopackets.RemoteErrorPacket.ErrorType.UNRECOGNIZED : result;
    }
    /**
     * <code>.RemoteErrorPacket.ErrorType errorType = 1;</code>
     * @param value The errorType to set.
     * @return This builder for chaining.
     */
    public Builder setErrorType(sendereCommons.protopackets.RemoteErrorPacket.ErrorType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      errorType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.RemoteErrorPacket.ErrorType errorType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorType() {
      
      errorType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object extraMessage_ = "";
    /**
     * <code>string extraMessage = 2;</code>
     * @return Whether the extraMessage field is set.
     */
    public boolean hasExtraMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>string extraMessage = 2;</code>
     * @return The extraMessage.
     */
    public java.lang.String getExtraMessage() {
      java.lang.Object ref = extraMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extraMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extraMessage = 2;</code>
     * @return The bytes for extraMessage.
     */
    public com.google.protobuf.ByteString
        getExtraMessageBytes() {
      java.lang.Object ref = extraMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extraMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extraMessage = 2;</code>
     * @param value The extraMessage to set.
     * @return This builder for chaining.
     */
    public Builder setExtraMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      extraMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extraMessage = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtraMessage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      extraMessage_ = getDefaultInstance().getExtraMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string extraMessage = 2;</code>
     * @param value The bytes for extraMessage to set.
     * @return This builder for chaining.
     */
    public Builder setExtraMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      extraMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RemoteErrorPacket)
  }

  // @@protoc_insertion_point(class_scope:RemoteErrorPacket)
  private static final sendereCommons.protopackets.RemoteErrorPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sendereCommons.protopackets.RemoteErrorPacket();
  }

  public static sendereCommons.protopackets.RemoteErrorPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemoteErrorPacket>
      PARSER = new com.google.protobuf.AbstractParser<RemoteErrorPacket>() {
    @java.lang.Override
    public RemoteErrorPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RemoteErrorPacket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RemoteErrorPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemoteErrorPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sendereCommons.protopackets.RemoteErrorPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

