// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package SendereCommons.protopackets;

public interface SendResponsePacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendResponsePacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 transmissionId = 1;</code>
   * @return The transmissionId.
   */
  long getTransmissionId();

  /**
   * <code>bool accepted = 2;</code>
   * @return The accepted.
   */
  boolean getAccepted();
}
