// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package sendereCommons.protopackets;

public interface SignedPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SignedPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes nestedPacketBytes = 1;</code>
   * @return The nestedPacketBytes.
   */
  com.google.protobuf.ByteString getNestedPacketBytes();

  /**
   * <code>bytes salt = 2;</code>
   * @return The salt.
   */
  com.google.protobuf.ByteString getSalt();

  /**
   * <code>bytes signature = 3;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
