// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping-packet.proto

package SendereCommons.protopackets;

/**
 * Protobuf type {@code TransmissionControlPacket}
 */
public final class TransmissionControlPacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TransmissionControlPacket)
    TransmissionControlPacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransmissionControlPacket.newBuilder() to construct.
  private TransmissionControlPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransmissionControlPacket() {
    signal_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransmissionControlPacket();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransmissionControlPacket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            transmissionId_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            signal_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SendereCommons.protopackets.PacketProtos.internal_static_TransmissionControlPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SendereCommons.protopackets.PacketProtos.internal_static_TransmissionControlPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SendereCommons.protopackets.TransmissionControlPacket.class, SendereCommons.protopackets.TransmissionControlPacket.Builder.class);
  }

  /**
   * Protobuf enum {@code TransmissionControlPacket.Signal}
   */
  public enum Signal
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SENDING_CANCELED = 0;</code>
     */
    SENDING_CANCELED(0),
    /**
     * <code>RECEIVING_CANCELED = 1;</code>
     */
    RECEIVING_CANCELED(1),
    /**
     * <code>SENDING_COMPLETE = 2;</code>
     */
    SENDING_COMPLETE(2),
    /**
     * <code>RECEIVING_COMPLETE = 3;</code>
     */
    RECEIVING_COMPLETE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SENDING_CANCELED = 0;</code>
     */
    public static final int SENDING_CANCELED_VALUE = 0;
    /**
     * <code>RECEIVING_CANCELED = 1;</code>
     */
    public static final int RECEIVING_CANCELED_VALUE = 1;
    /**
     * <code>SENDING_COMPLETE = 2;</code>
     */
    public static final int SENDING_COMPLETE_VALUE = 2;
    /**
     * <code>RECEIVING_COMPLETE = 3;</code>
     */
    public static final int RECEIVING_COMPLETE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Signal valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Signal forNumber(int value) {
      switch (value) {
        case 0: return SENDING_CANCELED;
        case 1: return RECEIVING_CANCELED;
        case 2: return SENDING_COMPLETE;
        case 3: return RECEIVING_COMPLETE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Signal>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Signal> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Signal>() {
            public Signal findValueByNumber(int number) {
              return Signal.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SendereCommons.protopackets.TransmissionControlPacket.getDescriptor().getEnumTypes().get(0);
    }

    private static final Signal[] VALUES = values();

    public static Signal valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Signal(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TransmissionControlPacket.Signal)
  }

  public static final int TRANSMISSIONID_FIELD_NUMBER = 1;
  private long transmissionId_;
  /**
   * <code>int64 transmissionId = 1;</code>
   * @return The transmissionId.
   */
  @java.lang.Override
  public long getTransmissionId() {
    return transmissionId_;
  }

  public static final int SIGNAL_FIELD_NUMBER = 2;
  private int signal_;
  /**
   * <code>.TransmissionControlPacket.Signal signal = 2;</code>
   * @return The enum numeric value on the wire for signal.
   */
  @java.lang.Override public int getSignalValue() {
    return signal_;
  }
  /**
   * <code>.TransmissionControlPacket.Signal signal = 2;</code>
   * @return The signal.
   */
  @java.lang.Override public SendereCommons.protopackets.TransmissionControlPacket.Signal getSignal() {
    @SuppressWarnings("deprecation")
    SendereCommons.protopackets.TransmissionControlPacket.Signal result = SendereCommons.protopackets.TransmissionControlPacket.Signal.valueOf(signal_);
    return result == null ? SendereCommons.protopackets.TransmissionControlPacket.Signal.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (transmissionId_ != 0L) {
      output.writeInt64(1, transmissionId_);
    }
    if (signal_ != SendereCommons.protopackets.TransmissionControlPacket.Signal.SENDING_CANCELED.getNumber()) {
      output.writeEnum(2, signal_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (transmissionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, transmissionId_);
    }
    if (signal_ != SendereCommons.protopackets.TransmissionControlPacket.Signal.SENDING_CANCELED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, signal_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SendereCommons.protopackets.TransmissionControlPacket)) {
      return super.equals(obj);
    }
    SendereCommons.protopackets.TransmissionControlPacket other = (SendereCommons.protopackets.TransmissionControlPacket) obj;

    if (getTransmissionId()
        != other.getTransmissionId()) return false;
    if (signal_ != other.signal_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSMISSIONID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTransmissionId());
    hash = (37 * hash) + SIGNAL_FIELD_NUMBER;
    hash = (53 * hash) + signal_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SendereCommons.protopackets.TransmissionControlPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SendereCommons.protopackets.TransmissionControlPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TransmissionControlPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TransmissionControlPacket)
      SendereCommons.protopackets.TransmissionControlPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SendereCommons.protopackets.PacketProtos.internal_static_TransmissionControlPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SendereCommons.protopackets.PacketProtos.internal_static_TransmissionControlPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SendereCommons.protopackets.TransmissionControlPacket.class, SendereCommons.protopackets.TransmissionControlPacket.Builder.class);
    }

    // Construct using SendereCommons.protopackets.TransmissionControlPacket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      transmissionId_ = 0L;

      signal_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SendereCommons.protopackets.PacketProtos.internal_static_TransmissionControlPacket_descriptor;
    }

    @java.lang.Override
    public SendereCommons.protopackets.TransmissionControlPacket getDefaultInstanceForType() {
      return SendereCommons.protopackets.TransmissionControlPacket.getDefaultInstance();
    }

    @java.lang.Override
    public SendereCommons.protopackets.TransmissionControlPacket build() {
      SendereCommons.protopackets.TransmissionControlPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public SendereCommons.protopackets.TransmissionControlPacket buildPartial() {
      SendereCommons.protopackets.TransmissionControlPacket result = new SendereCommons.protopackets.TransmissionControlPacket(this);
      result.transmissionId_ = transmissionId_;
      result.signal_ = signal_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SendereCommons.protopackets.TransmissionControlPacket) {
        return mergeFrom((SendereCommons.protopackets.TransmissionControlPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SendereCommons.protopackets.TransmissionControlPacket other) {
      if (other == SendereCommons.protopackets.TransmissionControlPacket.getDefaultInstance()) return this;
      if (other.getTransmissionId() != 0L) {
        setTransmissionId(other.getTransmissionId());
      }
      if (other.signal_ != 0) {
        setSignalValue(other.getSignalValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SendereCommons.protopackets.TransmissionControlPacket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SendereCommons.protopackets.TransmissionControlPacket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long transmissionId_ ;
    /**
     * <code>int64 transmissionId = 1;</code>
     * @return The transmissionId.
     */
    @java.lang.Override
    public long getTransmissionId() {
      return transmissionId_;
    }
    /**
     * <code>int64 transmissionId = 1;</code>
     * @param value The transmissionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransmissionId(long value) {
      
      transmissionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 transmissionId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransmissionId() {
      
      transmissionId_ = 0L;
      onChanged();
      return this;
    }

    private int signal_ = 0;
    /**
     * <code>.TransmissionControlPacket.Signal signal = 2;</code>
     * @return The enum numeric value on the wire for signal.
     */
    @java.lang.Override public int getSignalValue() {
      return signal_;
    }
    /**
     * <code>.TransmissionControlPacket.Signal signal = 2;</code>
     * @param value The enum numeric value on the wire for signal to set.
     * @return This builder for chaining.
     */
    public Builder setSignalValue(int value) {
      
      signal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.TransmissionControlPacket.Signal signal = 2;</code>
     * @return The signal.
     */
    @java.lang.Override
    public SendereCommons.protopackets.TransmissionControlPacket.Signal getSignal() {
      @SuppressWarnings("deprecation")
      SendereCommons.protopackets.TransmissionControlPacket.Signal result = SendereCommons.protopackets.TransmissionControlPacket.Signal.valueOf(signal_);
      return result == null ? SendereCommons.protopackets.TransmissionControlPacket.Signal.UNRECOGNIZED : result;
    }
    /**
     * <code>.TransmissionControlPacket.Signal signal = 2;</code>
     * @param value The signal to set.
     * @return This builder for chaining.
     */
    public Builder setSignal(SendereCommons.protopackets.TransmissionControlPacket.Signal value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      signal_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.TransmissionControlPacket.Signal signal = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignal() {
      
      signal_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TransmissionControlPacket)
  }

  // @@protoc_insertion_point(class_scope:TransmissionControlPacket)
  private static final SendereCommons.protopackets.TransmissionControlPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SendereCommons.protopackets.TransmissionControlPacket();
  }

  public static SendereCommons.protopackets.TransmissionControlPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransmissionControlPacket>
      PARSER = new com.google.protobuf.AbstractParser<TransmissionControlPacket>() {
    @java.lang.Override
    public TransmissionControlPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransmissionControlPacket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransmissionControlPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransmissionControlPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public SendereCommons.protopackets.TransmissionControlPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

